;;;
;;;  ZEDIAC 65C22 VIA DEFINES
;;;
;;; (C) Ray Clemens 2023
;;;
;;; Updates:
;;; 2023-05-16: Created file (Copied from EMMA-2 source)
;;;
;;;


;; #ifndef VIA_INC
;; #define VIA_INC

VIA_ORB     .equ 0
VIA_IRB     .equ 0
VIA_ORA     .equ 1
VIA_IRA     .equ 1
VIA_DDRB    .equ 2
VIA_DDRA    .equ 3
VIA_T1CL    .equ 4
VIA_T1CH    .equ 5
VIA_T1LL    .equ 6
VIA_T1LH    .equ 7
VIA_T2CL    .equ 8
VIA_T2CH    .equ 9
VIA_SR      .equ 10
VIA_ACR     .equ 11
VIA_PCR     .equ 12
VIA_IFR     .equ 13
VIA_IER     .equ 14
VIA_ORAF    .equ 15
VIA_IRAF    .equ 15

;; #endif
